{
 "title": "Dude Dashboard 2",
 "time": { "from": "2024-05-19T09:14:01.763Z", "to": "2024-05-19T09:14:18.782Z" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"array\"\nimport \"experimental/geo\"\n\ndata =\n    from(bucket: \"dude\")\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n        |> filter(fn: (r) => r._measurement == \"avionic\")\n        |> filter(fn: (r) => r._field == \"lat\" or r._field == \"lon\")\n\ntotalDistance = (tables=<-) =>\n    tables\n        |> reduce(\n            identity: {\n                index: 0,\n                lat: 0.0,\n                lon: 0.0,\n                totalDistance: 0.0,\n            },\n            fn: (r, accumulator) => {\n                lastPoint =\n                    if accumulator.index == 0 then\n                        {lat: r.lat, lon: r.lon}\n                    else\n                        {lat: accumulator.lat, lon: accumulator.lon}\n                currentPoint = {lat: r.lat, lon: r.lon}\n\n                return {\n                    index: accumulator.index + 1,\n                    lat: r.lat,\n                    lon: r.lon,\n                    totalDistance:\n                        accumulator.totalDistance + geo.ST_Distance(region: lastPoint, geometry: currentPoint),\n                }\n            },\n        )\n        |> drop(columns: [\"index\", \"lat\", \"lon\"])\n\ndata\n    |> geo.shapeData(latField: \"lat\", lonField: \"lon\", level: 20)\n    |> group(columns: [\"id\"])\n    |> totalDistance()\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Geo",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 24, "w": 11, "x": 0, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"dude\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"avionic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"lat\" or r[\"_field\"] == \"lon\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Engine",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"dude\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"engine\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avionic",
   "type": "graph",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"dude\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"avionic\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}