{
 "title": "Premier",
 "time": { "from": "2024-06-22T04:30:03.756Z", "to": "2024-06-22T04:31:06.000Z" },
 "panels": [
  {
   "title": "Geo",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 24, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"dude\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"avionic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"lat\" or r[\"_field\"] == \"lon\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Engine",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"dude\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"engine\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Amps\" or r[\"_field\"] == \"ChtLeftTemperaturedegC\" or r[\"_field\"] == \"ChtRightTemperaturedegC\" or r[\"_field\"] == \"EGT1degC\" or r[\"_field\"] == \"EGT2degC\" or r[\"_field\"] == \"FuelPressurePSI\" or r[\"_field\"] == \"ManifoldPressureinHg\" or r[\"_field\"] == \"OilPressurePSI:\" or r[\"_field\"] == \"OilTempdegC\" or r[\"_field\"] == \"RPM\" or r[\"_field\"] == \"TotalFuelFlowgalhr\" or r[\"_field\"] == \"Volts1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avionic",
   "type": "graph",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"dude\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"avionic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TotalFuelFlowgalhr\" or r[\"_field\"] == \"RPM\" or r[\"_field\"] == \"ManifoldPressureinHg\" or r[\"_field\"] == \"Amps\" or r[\"_field\"] == \"ChtLeftTemperaturedegC\" or r[\"_field\"] == \"ChtRightTemperaturedegC\" or r[\"_field\"] == \"EGT1degC\" or r[\"_field\"] == \"EGT2degC\" or r[\"_field\"] == \"FuelPressurePSI\" or r[\"_field\"] == \"GroundSpeedknots\" or r[\"_field\"] == \"IndicatedAirspeedknots\" or r[\"_field\"] == \"LateralAccelg\" or r[\"_field\"] == \"MagneticHeadingdeg\" or r[\"_field\"] == \"OATdegC\" or r[\"_field\"] == \"OilPressurePSI:\" or r[\"_field\"] == \"OilTempdegC\" or r[\"_field\"] == \"Pitchdeg\" or r[\"_field\"] == \"Rolldeg\" or r[\"_field\"] == \"TrueAirspeedknots\" or r[\"_field\"] == \"VerticalAccelg\" or r[\"_field\"] == \"VerticalSpeedftmin\" or r[\"_field\"] == \"Volts1\" or r[\"_field\"] == \"alt\" or r[\"_field\"] == \"lat\" or r[\"_field\"] == \"lon\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}