apiVersion: 1

datasources:
  - name: influxdb
    type: "influxdb"
    access: "proxy"
    url: "http://dude-influxdb:8086"
    editable: true
    secureJsonData:
      token: "my-super-secret-auth-token"
    jsonData:
      version: Flux
      organization: "dude"
      defaultBucket: dude
      tlsSkipVerify: true
      timeInterval: "1s"

